#!/usr/bin/env python3
"""Platform Report Templates — render bug bounty reports for HackerOne, Bugcrowd, or generic disclosure.

Usage:
    platform_templates.py render --finding-dir evidence/finding_001 --platform hackerone --output report.md
    platform_templates.py list-fields --platform hackerone
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def now_date() -> str:
    return datetime.now(timezone.utc).strftime("%B %d, %Y")


# Templates use @PLACEHOLDER@ syntax to avoid JSON/escape issues
HACKERONE_TEMPLATE = """# @TITLE@

**Reporter:** @REPORTER@
**Date:** @DATE@
**Program:** @PROGRAM@
**Severity:** @SEVERITY@
**CVSS:** @CVSS_SCORE@ (@CVSS_VECTOR@)
**URL:** @TARGET_URL@

## Summary

@SUMMARY@

## Steps to Reproduce

@REPRO_STEPS@

## Proof of Concept

@POC@

## Impact

@IMPACT@

## Affected Assets

@AFFECTED_ASSETS@

## Remediation

@REMEDIATION@

## References

@REFERENCES@

---
*Generated by BountyHarness v3.0.0*
"""

BUGCROWD_TEMPLATE = """# @TITLE@

## Vulnerability Details

- **Type:** @VULN_TYPE@
- **Severity:** @SEVERITY@
- **CVSS Score:** @CVSS_SCORE@
- **CVSS Vector:** @CVSS_VECTOR@
- **Target:** @TARGET_URL@
- **Date Reported:** @DATE@

## Description

@SUMMARY@

## Steps to Reproduce

@REPRO_STEPS@

## Proof of Concept

@POC@

## Impact

@IMPACT@

## Affected Assets

@AFFECTED_ASSETS@

## Remediation Advice

@REMEDIATION@

## Supporting Evidence

@EVIDENCE_LIST@

---
*Generated by BountyHarness v3.0.0*
"""

GENERIC_TEMPLATE = """# Security Vulnerability Report: @TITLE@

**Reported by:** @REPORTER@
**Date:** @DATE@
**Organization:** @PROGRAM@
**Severity:** @SEVERITY@ (CVSS: @CVSS_SCORE@)

## Executive Summary

@SUMMARY@

## Technical Details

### Vulnerability Type
@VULN_TYPE@

### Affected URL / Endpoint
@TARGET_URL@

### Steps to Reproduce
@REPRO_STEPS@

### Proof of Concept
@POC@

## Impact Assessment

@IMPACT@

## Affected Systems

@AFFECTED_ASSETS@

## Recommended Remediation

@REMEDIATION@

## Disclosure Timeline

- **Reported:** @DATE@
- **Acknowledged:** _Pending_
- **Fixed:** _Pending_
- **Public Disclosure:** _Pending coordination_

## References

@REFERENCES@

---
*This report was prepared using BountyHarness.*
"""

TEMPLATES = {
    "hackerone": HACKERONE_TEMPLATE,
    "bugcrowd": BUGCROWD_TEMPLATE,
    "generic": GENERIC_TEMPLATE,
}


def load_evidence(finding_dir: str) -> Dict[str, Any]:
    d = Path(finding_dir)
    evidence = {
        "title": "Untitled Finding",
        "summary": "",
        "repro_steps": "",
        "poc": "",
        "impact": "",
        "affected_assets": "",
        "remediation": "",
        "references": "",
        "severity": "medium",
        "cvss_score": "0.0",
        "cvss_vector": "",
        "target_url": "",
        "vuln_type": "",
        "reporter": "Anonymous Researcher",
        "program": "",
        "date": now_date(),
        "evidence_list": "",
    }

    manifest = d / "manifest.json"
    if manifest.exists():
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
            evidence.update(data)
        except Exception:
            pass

    req = d / "request.txt"
    if req.exists():
        evidence["request"] = req.read_text(encoding="utf-8")

    resp = d / "response.txt"
    if resp.exists():
        evidence["response"] = resp.read_text(encoding="utf-8")

    imp = d / "impact.md"
    if imp.exists():
        evidence["impact"] = imp.read_text(encoding="utf-8")

    poc = d / "poc.sh"
    if poc.exists():
        evidence["poc"] = f"```bash\n{poc.read_text(encoding='utf-8')}\n```"

    evidence_files = []
    for f in sorted(d.iterdir()):
        if f.is_file():
            evidence_files.append(f"- `{f.name}`")
    evidence["evidence_list"] = "\n".join(evidence_files) if evidence_files else "No evidence files found."

    return evidence


def render_template(template_text: str, evidence: Dict[str, Any]) -> str:
    result = template_text
    for key, value in evidence.items():
        placeholder = f"@{key.upper().replace(' ', '_')}@"
        result = result.replace(placeholder, str(value) if value is not None else "")
    result = re.sub(r"@[A-Z_]+@", "", result)
    return result


def render_report(finding_dir: str, platform: str) -> str:
    if platform not in TEMPLATES:
        raise ValueError(f"Unknown platform: {platform}. Choose from: {', '.join(TEMPLATES.keys())}")
    evidence = load_evidence(finding_dir)
    template = TEMPLATES[platform]
    return render_template(template, evidence)


def list_required_fields(platform: str) -> list:
    if platform not in TEMPLATES:
        raise ValueError(f"Unknown platform: {platform}")
    template = TEMPLATES[platform]
    fields = re.findall(r"@([A-Z_]+)@", template)
    return sorted(set(fields))


def main():
    parser = argparse.ArgumentParser(description="Platform Report Templates")
    sub = parser.add_subparsers(dest="command", help="Commands")

    p_render = sub.add_parser("render", help="Render a report from evidence")
    p_render.add_argument("--finding-dir", required=True, help="Finding evidence directory")
    p_render.add_argument("--platform", required=True, choices=list(TEMPLATES.keys()), help="Target platform")
    p_render.add_argument("--output", required=True, help="Output markdown file")

    p_list = sub.add_parser("list-fields", help="List required fields for a platform")
    p_list.add_argument("--platform", required=True, choices=list(TEMPLATES.keys()), help="Target platform")

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "render":
        report = render_report(args.finding_dir, args.platform)
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(report, encoding="utf-8")
        print(json.dumps({"status": "rendered", "platform": args.platform, "output": args.output}))

    elif args.command == "list-fields":
        fields = list_required_fields(args.platform)
        for f in fields:
            print(f)


if __name__ == "__main__":
    main()
